Começando alteração Introdução e problema
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e3-proj-mov-t3-grupo2 pull request #2
Opened 2023-03-24 14:57 UTC by flavio1904

Alterações iniciais

2023-03-24 21:17 UTC, jramiresbrito requested changes

2023-03-24 21:17 UTC, jramiresbrito commented on docs/01-Documentação de Contexto.md
> +A internet é uma rede global de conexões que utilizam um conjunto próprio de protocolos com o objetivo de servir usuários do mundo inteiro, permitindo um compartilhamento instantâneo de dados entre d
> ....20 mil novos sites por dia

Ficou redundante pois você inicia a frase com *Todos os dias*

Basta tirar por dia ficando assim

> Todos os dias, segundo um levantamento realizado pela BigWeb, que é uma ferramenta de varredura da internet, são criados aproximadamente 20 mil novos sites, e devido a falta de manutenção dada pelos seus criadores, esse site é considerado morto.

No entanto essa parte de falar sobre a falta de manutenção e dizer que o site é considerado morto, me pareceu um pouco fora do contexto do problema.

Eu reformularia para o seguinte

> Todos os dias, segundo um levantamento realizado pela BigWeb, que é uma ferramenta de varredura da internet, são criados aproximadamente 20 mil novos sites dos mais diversos tipos. Com a veiculação de conteúdo ocorrendo de forma tão distribuída, passa a ser uma tarefa bastante árdua a centralização de conteúdo especializado sobre um determinado assunto.

2023-03-24 21:17 UTC, jramiresbrito commented on docs/01-Documentação de Contexto.md
> +Com esse grande número de sites sendo criados todos os dias, chega o problema que no Brasil é conhecido como "Fake News", que segundo o dicionário são "Notícias falsas ou informações mentirosas que s
Eu gostaria de evitar trazer o uso de Fake News aqui pois o viés da aplicação não é fornecer um conteúdo com curadoria, O objetivo é, simplesmente, a centralização de conteúdos sobre determinado assunto.

Talvez poderíamos falar algo como

> Com esse grande número de sites sendo criados todos os dias, pessoas interessadas em aprofundar um assunto podem ter bastante dificuldade buscando informações em diversas fontes. Portanto, uma solução que visa a centralização de conteúdo mostra-se bastante relevante.

2023-03-25 17:23 UTC, joicepassos commented on docs/01-Documentação de Contexto.md
> +Com esse grande número de sites sendo criados todos os dias, chega o problema que no Brasil é conhecido como "Fake News", que segundo o dicionário são "Notícias falsas ou informações mentirosas que s
Concordo com a fala do João, ao citar fake news acabamos trazendo uma necessidade de curadoria para os requisitos do aplicativo, o que seria complexo dado ao tempo de desenvolvimento que temos, deixo como sugestão, pautarmos essa parte trazendo a tona o crescimento da procura da polução em assuntos financeiros e em como esse mercado passou a crescer, isso vai dar um viés interessante já pra ser usado na justificativa e não adicionamos nenhum requisito no desenvolvimento,

2023-04-17 03:00 UTC, closed without merging